
/*1) Without Intersect*/
SELECT ACTOR.ACT_FIRSTNAME,ACTOR.ACT_LASTNAME FROM ACTOR,DIRECTOR WHERE ACTOR.ACT_FIRSTNAME=DIRECTOR.DIR_FIRSTNAME AND ACTOR.ACT_LASTNAME=DIRECTOR.DIR_LASTNAME;
/*1) With Intersect*/
SELECT ACTOR.ACT_FIRSTNAME,ACTOR.ACT_LASTNAME FROM ACTOR INTERSECT SELECT DIRECTOR.DIR_FIRSTNAME,DIRECTOR.DIR_LASTNAME FROM DIRECTOR;

/*2)*/
SELECT ACTOR.ACT_FIRSTNAME AS FIRSTNAME FROM ACTOR UNION SELECT DIRECTOR.DIR_FIRSTNAME AS FIRSTNAME FROM DIRECTOR;


/*3) Without minus*/
SELECT MOV_TITLE  FROM MOVIE WHERE MOV_ID NOT IN (SELECT MOV_ID FROM RATING);
/*3) With minus*/
SELECT MOV_TITLE FROM MOVIE WHERE MOV_ID IN  (SELECT MOV_ID FROM MOVIE minus SELECT MOV_ID FROM RATING);

/*4) */
SELECT avg(nvl(REV_STARS,0)) FROM MOVIE,RATING WHERE MOVIE.MOV_ID=RATING.MOV_ID;


/*5)*/
SELECT MOV_ID,min(REV_STARS) AS MINIMUM_RATING FROM RATING group by MOV_ID order by min(REV_STARS) desc;


/*6)*/
SELECT ACT_LASTNAME,count(REV_STARS) FROM ((ACTOR NATURAL JOIN CASTS) NATURAL JOIN (MOVIE NATURAL JOIN RATING)) GROUP BY ACT_LASTNAME;

/*7) Without having clause*/
SELECT ACT_LASTNAME,avg(MOV_TIME) FROM(((ACTOR NATURAL JOIN CASTS) NATURAL JOIN (DIRECTOR NATURAL JOIN DIRECTION)) NATURAL JOIN (MOVIE NATURAL JOIN RATING)) WHERE DIR_FIRSTNAME<>'James' AND DIR_LASTNAME<>'Cameron' GROUP BY ACT_LASTNAME;

/*7) With having clause*/
SELECT distinct ACT_LASTNAME,avg(MOV_TIME) FROM(((ACTOR NATURAL JOIN CASTS) NATURAL JOIN (DIRECTOR NATURAL JOIN DIRECTION)) NATURAL JOIN (MOVIE NATURAL JOIN RATING)) 
GROUP BY ACT_LASTNAME,DIR_FIRSTNAME,DIR_LASTNAME HAVING DIR_FIRSTNAME<>'James' AND DIR_LASTNAME<>'Cameron';

/*8) Without ALL*/
SELECT DIR_FIRSTNAME,DIR_LASTNAME FROM ((
(DIRECTOR NATURAL JOIN DIRECTION) 
NATURAL JOIN 
(SELECT MOV_ID,avg(REV_STARS)REVIEW FROM MOVIE NATURAL JOIN RATING GROUP BY MOV_ID)
) NATURAL JOIN (SELECT MAX(REVIEW)REVIEW FROM (
(DIRECTOR NATURAL JOIN DIRECTION) 
NATURAL JOIN 
(SELECT MOV_ID,avg(REV_STARS)REVIEW FROM MOVIE NATURAL JOIN RATING GROUP BY MOV_ID)
)));

/*8) With ALL*/
SELECT DIR_FIRSTNAME, DIR_LASTNAME FROM ((DIRECTOR NATURAL JOIN DIRECTION))NATURAL JOIN 
((SELECT MOV_ID,avg(REV_STARS)REVIEW FROM MOVIE NATURAL JOIN RATING GROUP BY MOV_ID)) GROUP BY DIR_FIRSTNAME,DIR_LASTNAME,REVIEW,MOV_ID HAVING 
REVIEW>=all(SELECT REVIEW FROM ((DIRECTOR NATURAL JOIN DIRECTION))NATURAL JOIN 
((SELECT MOV_ID,avg(REV_STARS)REVIEW FROM MOVIE NATURAL JOIN RATING GROUP BY MOV_ID)));



/*9)*/
SELECT MOV_ID,MOV_TITLE,MOV_YEAR,MOV_LANGUAGE,MOV_RELEASEDATE,MOV_COUNTRY FROM (((ACTOR NATURAL JOIN CASTS) NATURAL JOIN (DIRECTOR NATURAL JOIN DIRECTION) NATURAL JOIN MOVIE)) WHERE ACT_FIRSTNAME=DIR_FIRSTNAME AND ACT_LASTNAME=DIR_LASTNAME;

/*10)* Without Having Clause*/
SELECT MOV_TITLE,REVIEW FROM MOVIE NATURAL JOIN (SELECT MOV_ID,avg(REV_STARS)REVIEW FROM MOVIE NATURAL JOIN RATING GROUP BY MOV_ID) WHERE REVIEW>7;

/*10)* With Having Clause*/
SELECT MOV_TITLE,REVIEW FROM MOVIE NATURAL JOIN (SELECT MOV_ID,avg(REV_STARS)REVIEW FROM MOVIE NATURAL JOIN RATING GROUP BY MOV_ID) GROUP BY REVIEW,MOV_TITLE HAVING REVIEW>7;

/*11)*/
SELECT MOV_TITLE,avg(nvl(REV_STARS,0))REVIEW FROM MOVIE NATURAL JOIN RATING GROUP BY MOV_ID,MOV_TITLE HAVING avg(nvl(REV_STARS,0))>(SELECT avg(nvl(REV_STARS,0)) FROM MOVIE NATURAL JOIN RATING); 

/*12)*/
SELECT DISTINCT MOV_TITLE,(SELECT AVG(NVL(REV_STARS,0))
                        FROM RATING
                        WHERE MOVIE.MOV_ID = RATING.MOV_ID)RATING
FROM MOVIE, RATING
WHERE MOVIE.MOV_ID = RATING.MOV_ID;

/*13)*/
SELECT ACT_FIRSTNAME FROM ACTOR WHERE ACT_GENDER='F' GROUP BY ACT_FIRSTNAME HAVING count(*)>1;

/*14)*/

SELECT MOV_ID,MOV_TITLE,MAX(REV_STARS) FROM (
    ((SELECT * FROM ACTOR WHERE ACT_GENDER='F') NATURAL JOIN CASTS) NATURAL JOIN 
    (
        (SELECT MOV_TITLE,MOV_ID FROM MOVIE NATURAL JOIN RATING GROUP BY MOV_ID,MOV_TITLE HAVING COUNT(*)>=10) 
        NATURAL JOIN(
            DIRECTION 
            NATURAL JOIN
        (SELECT DIR_ID FROM DIRECTOR NATURAL JOIN DIRECTION GROUP BY DIR_ID HAVING COUNT(DIR_ID)>=1)
        )
    ) NATURAL JOIN (
    (SELECT * FROM RATING NATURAL JOIN REVIEWER WHERE REV_NAME='Neal Wruck' AND REV_STARS>4)
    )
    )
        GROUP BY MOV_ID,MOV_TITLE;



