DROP SEQUENCE STUDENT_SEQ;
CREATE SEQUENCE STUDENT_SEQ
MINVALUE 00000
MAXVALUE 99999
START WITH 1
INCREMENT BY 1
CACHE 100;

CREATE OR REPLACE TRIGGER STUDENT_ID_GENERATOR
BEFORE INSERT
   ON STUDENT
   FOR EACH ROW
BEGIN
   SELECT STUDENT_SEQ . NEXTVAL INTO :NEW.ID FROM DUAL ;
END;

/


begin
  insert into student(NAME,DEPT_NAME,TOT_CRED) values ('Zhang', 'Comp. Sci.', '102');
end;

