SET SERVEROUTPUT ON SIZE 1000000
CREATE OR REPLACE FUNCTION POPULAR_GENRE(START_DATE IN MOVIE.MOV_RELEASEDATE%TYPE , END_DATE IN MOVIE.MOV_RELEASEDATE%TYPE)
RETURN varchar2
AS
  count_mov number;
  genre varchar2(200);
  genre_id GENRES.GEN_ID%TYPE;
BEGIN
    SELECT id INTO genre_id FROM (SELECT MTYPE.gen_id AS id,count(MOVIES_IN_TIME.MOV_ID) AS mov_count FROM (
    SELECT * FROM MOVIE WHERE MOVIE.MOV_RELEASEDATE BETWEEN START_DATE AND END_DATE
    )MOVIES_IN_TIME,MTYPE WHERE MOVIES_IN_TIME.MOV_ID=MTYPE.MOV_ID GROUP BY MTYPE.gen_id ORDER BY mov_count DESC)filter_gen WHERE ROWNUM<=1;
    SELECT GEN_TITLE INTO genre FROM GENRES WHERE GEN_ID=genre_id;
    SELECT count(MOVIE.MOV_ID) INTO count_mov FROM MOVIE,MTYPE WHERE MOVIE.MOV_ID=MTYPE.MOV_ID AND MTYPE.gen_id=genre_id AND MOVIE.MOV_RELEASEDATE BETWEEN START_DATE AND END_DATE;  
  RETURN genre||', count of movies released: '||count_mov;  
END;
/

DECLARE
    start_date MOVIE.MOV_RELEASEDATE%TYPE;
    end_date MOVIE.MOV_RELEASEDATE%TYPE;
BEGIN
    start_date:='&start_date';
    end_date:='&end_date';
    DBMS_OUTPUT.PUT_LINE(POPULAR_GENRE(TO_DATE(start_date),TO_DATE(end_date)));
END;
/