SET SERVEROUTPUT ON SIZE 1000000
CREATE OR REPLACE FUNCTION GET_YEARLY_EARNING(title IN MOVIE.MOV_TITLE%TYPE)
RETURN NUMBER
AS
INCOME NUMBER;
YEARS_ELAPSED NUMBER;
CURR_YEAR NUMBER;
BEGIN
  SELECT EXTRACT(YEAR FROM (MOV_RELEASEDATE)) INTO YEARS_ELAPSED FROM MOVIE WHERE MOV_TITLE=title;
  SELECT COUNT(*)*10 INTO INCOME FROM MOVIE,RATING WHERE MOVIE.MOV_ID=RATING.MOV_ID AND RATING.REV_STARS>6;
  SELECT EXTRACT(Year FROM SYSDATE) INTO CURR_YEAR FROM Dual;
  YEARS_ELAPSED:=CURR_YEAR-YEARS_ELAPSED;
  RETURN TRUNC(INCOME/YEARS_ELAPSED,4);
END;
/

DECLARE
    mov_title movie.mov_title%TYPE;
BEGIN
    mov_title:='&something';
    DBMS_OUTPUT.PUT_LINE(GET_YEARLY_EARNING(mov_title));
END;
/