SET SERVEROUTPUT ON SIZE 1000000
CREATE OR REPLACE PROCEDURE get_top_rated_movies(N IN number)
AS
ROWS number;
begin
  SELECT count(*) INTO ROWS FROM (SELECT MOVIE.MOV_TITLE AS TITLE,MOVIE.MOV_ID,avg(RATING.REV_STARS)  FROM MOVIE,RATING WHERE MOVIE.MOV_ID=RATING.MOV_ID GROUP BY MOVIE.MOV_ID,MOVIE.MOV_TITLE,RATING.REV_STARS ORDER BY avg(RATING.REV_STARS) DESC);
  IF(N>ROWS) THEN
    DBMS_OUTPUT.PUT_LINE('N greater than rows');
    RETURN;
  END IF;
  FOR i IN (SELECT TITLE FROM (SELECT MOVIE.MOV_TITLE AS TITLE,MOVIE.MOV_ID,avg(RATING.REV_STARS)  FROM MOVIE,RATING WHERE MOVIE.MOV_ID=RATING.MOV_ID GROUP BY MOVIE.MOV_ID,MOVIE.MOV_TITLE,RATING.REV_STARS ORDER BY avg(RATING.REV_STARS) DESC) WHERE ROWNUM<=N) LOOP
    dbms_output.put_line(i.TITLE);
  END LOOP;

end;
/

DECLARE
    rating number;
BEGIN
    rating:='&number';
    get_top_rated_movies(rating);
END;
/