
--Task-a-- 
SELECT * FROM DIVISION,(SELECT DivisionName,count(DivisionName)DistrictCount FROM DISTRICT GROUP BY DIVISION)DistrictDivision WHERE DIVISION.DivisionName=DistrictDivision.DivisionName;

--Task-b--
SELECT DISTRICT.DistrictName,count(DISTRICT.DistrictName)Population FROM DISTRICT,CITIZEN WHERE DISTRICT.DistrictName=CITIZEN.DistrictName AND DISTRICT.DistrictSize=CITIZEN.DistrictSize GROUP BY DISTRICT.DistrictName;

--Task-c--
SELECT count(*)NumberOfAccidents FROM ACCIDENT_LICENSE,CITIZEN WHERE ACCIDENT_LICENSE.NID='210' AND CITIZEN.NID='210' GROUP BY CITIZEN.NID;

--Task-d--
SELECT * FROM (SELECT HospitalName,count(*)NumberOfPatients FROM HOSPITAL,PATIENT WHERE HOSPITAL.Name=PATIENT.HospitalName GROUP BY HospitalName ORDER BY DESC) WHERE ROWNUM<=5;

--Task-e--
SELECT CITIZEN.BloodGroup FROM CITIZEN,PATIENT WHERE CITIZEN.NID=PATIENT.NID;

--Task-f--
SELECT count(*) FROM DISTRICT,DIVISION,CITIZEN WHERE DISTRICT.DistrictName=CITIZEN.DistrictName and DISTRICT.DivisionName=DIVISION.DivisionName;

--Task-g--
SELECT * FROM (SELECT count(*)Population FROM DISTRICT,DIVISION,CITIZEN WHERE DISTRICT.DistrictName=CITIZEN.DistrictName and DISTRICT.DivisionName=DIVISION.DivisionName ORDER BY Population DESC) WHERE ROWNUM<=5;

--Task-h--
SELECT DISTRICT.DistrictName,DISTRICT.DistrictSize,count(*)AccidentsPerDistrict FROM ACCIDENT,DISTRICT WHERE ACCIDENT.DistrictName=DISTRICT.DistrictName and ACCIDENT.DistrictSize=DISTRICT.DistrictSize GROUP BY DISTRICT.DistrictName,DISTRICT.DistrictSize;

--Task-i--
SELECT DIVISION.DivisionName FROM DISTRICT,DIVISION,ACCIDENT WHERE ACCIDENT.DistrictName=DISTRICT.DistrictName and ACCIDENT.DistrictSize=DISTRICT.DistrictSize and DISTRICT.DivisionName=DIVISION.DivisionName and DISTRICT.DivisionSize=DIVISION.DivisionSize GROUP BY DIVISION.DivisionName;

--Task-j--
SELECT LicenseType,count(*)NumberOfAccidents FROM ACCIDENT_LICENSE JOIN LICENSE ON ACCIDENT_LICENSE.NID=LICENSE.NID GROUP BY LICENSE.LicenseType;

--Task-k--
SELECT CITIZEN.NID,max(PATIENT.ReleaseDate-PATIENT.DateOfAdmission) FROM CITIZEN,PATIENT WHERE CITIZEN.NID=PATIENT.NID GROUP BY CITIZEN.NID,PATIENT.ReleaseDate,PATIENT.DateOfAdmission;


--Task-l--
SELECT min(YoungPopulation) FROM (select count(*)YoungPopulation FROM (SELECT CITIZEN.NID,CITIZEN.DistrictName,CITIZEN.DistrictSize,ROUND(((SELECT SYSDATE FROM DUAL)-DOB)/365) as AGE FROM CITIZEN),DISTRICT,DIVISION WHERE DISTRICT.DivisionName=DIVISION.DivisionName AND DISTRICT.DivisionSize=DIVISION.DivisionSize WHERE GROUP BY DIVISION.DivisionName,DIVISION.DivisionSize HAVING AGE>=15 AND AGE<=30);

--Task-m--
SELECT count(*)ExpiredLicenseCount FROM LICENSE WHERE (SELECT SYSDATE FROM DUAL)>LICENSE.ExpirationDate;

--Task-n--
SELECT count(*)NumberOfAccidentsByExpired FROM ACCIDENT_LICENSE,(SELECT * FROM LICENSE WHERE (SELECT SYSDATE FROM DUAL)>LICENSE.ExpirationDate)ExpiredLicenses WHERE ACCIDENT_LICENSE.NID=ExpiredLicenses.NID GROUP BY ACCIDENT_LICENSE.NID;

--Task-o--LicenseHolders or Active License Holders?
SELECT count(*) FROM (SELECT NID FROM LICENSE minus SELECT NID FROM ACCIDENT_LICENSE);

--Task-p--
SELECT DIVISION.DivisionName,DIVISION.DivisionSize,sum(numberOfDeaths) FROM ACCIDENT,DISTRICT,DIVISION WHERE ACCIDENT.DistrictName=DISTRICT.DistrictName AND ACCIDENT.DistrictSize=DISTRICT.DistrictSize AND DISTRICT.DivisionName=DIVISION.DivisionName AND DISTRICT.DivisionSize=DIVISION.DivisionSize GROUP BY DIVISION.DivisionName,DIVISION.DivisionSize;


--Task-q--
SELECT AGE FROM (SELECT ROUND(((LICENSE.IssueDate-CITIZEN.DOB)/365))AGE FROM LICENSE,CITIZEN WHERE LICENSE.NID=CITIZEN.NID) WHERE AGE<22 OR AGE>40;

--Task-r--
SELECT * FROM ACCIDENT_CITIZEN,PATIENT WHERE ACCIDENT_CITIZEN.NID=PATIENT.NID AND ACCIDENT_CITIZEN.dateOfAccident=PATIENT.DateOfAdmission;

--Task-s--
SELECT HOSPITAL.HospitalName,max(PatientCount) FROM (SELECT HOSPITAL.HospitalName,count(*)PatientCount FROM HOSPITAL,DISTRICT,DIVISION WHERE HOSPITAL.HospitalDistrictName=DISTRICT.DistrictName AND HOSPITAL.HospitalDistrictSize=DISTRICT.DistrictSize AND DISTRICT.DivisionName='Dhaka' GROUP BY HOSPITAL.HospitalName);

--Task-t--
SELECT * FROM ACCIDENT_CITIZEN,CITIZEN WHERE ACCIDENT_CITIZEN.NID=CITIZEN.NID AND ACCIDENT.DistrictName<>CITIZEN.DistrictName AND ACCIDENT.DistrictSize<>CITIZEN.DistrictSize;